### PR TITLE
Use GitBook instead of Sphinx

### PR DESCRIPTION
**Pull request by tschaub**
This uses the [`gitbook`](https://www.npmjs.com/package/gitbook) package instead of Sphinx to build the workshop.

This also more clearly separates the dev package from the participant package (they have separate `README.md` and `package.json`).

This may take more testing after merging, but Travis should also now build the release archive and attach it to the release page every time we push a tag.

### CODE REVIEW

**Comment by elemoine** [comment]
Cool.

**Comment by tschaub** [comment]
After merging, I'll test the Travis deploy by pushing a tag.

**Comment by marcjansen** [comment]
Very nice!

**Comment by bartvde** [comment]
Thanks Tim! Was interested to try out gitbook for a long time but good to see it happen.

**Pull request merged**
